name: GitHub Actions Trainee
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
        if: always()
      - name: linting typescript
        run: npm run lint
        if: always()
      - name: unit testing
        if: always()
        run: npm run test
      - name: build storybook
        run: npm run build-storybook
        if: always()
